build fuerza_bruta.cpp programacion_dinamica.cpp costos.cpp:
	g++ fuerza_bruta.cpp costos.cpp -o ./fuerza_bruta
	g++ programacion_dinamica.cpp costos.cpp -o ./programacion_dinamica

brute:
	./fuerza_bruta

dinamic:
	./programacion_dinamica

clean:
	rm -rf td fuerza_bruta programacion_dinamica
